In [42]:
import numpy as np
import pandas as pd
import sklearn as sk
import numpy as np
import sklearn.cross_validation as cross_validation
import sklearn.ensemble as ensemble
import sklearn.grid_search as grid_search
import sklearn.metrics as metrics
from sklearn.metrics import confusion_matrix
import pickle
import scipy.stats as stats
import matplotlib.pyplot as plt
%matplotlib inline

#Import and Combine Data

In [4]:
data1 = pd.read_csv('C:/Users/Mathew/Data Science Project/data/pums/ss13pusa.csv')

In [5]:
data2 = pd.read_csv('C:/Users/Mathew/Data Science Project/data/pums/ss13pusb.csv')

In [6]:
data = [data1, data2]
data = pd.concat(data)
print(data.shape)
del data1
del data2

(3132795, 283)


#Remove Non-Informational Features

In [7]:
data.columns.values

array(['RT', 'SERIALNO', 'SPORDER', 'PUMA', 'ST', 'ADJINC', 'PWGTP',
       'AGEP', 'CIT', 'CITWP', 'COW', 'DDRS', 'DEAR', 'DEYE', 'DOUT',
       'DPHY', 'DRAT', 'DRATX', 'DREM', 'ENG', 'FER', 'GCL', 'GCM', 'GCR',
       'HINS1', 'HINS2', 'HINS3', 'HINS4', 'HINS5', 'HINS6', 'HINS7',
       'INTP', 'JWMNP', 'JWRIP', 'JWTR', 'LANX', 'MAR', 'MARHD', 'MARHM',
       'MARHT', 'MARHW', 'MARHYP', 'MIG', 'MIL', 'MLPA', 'MLPB', 'MLPCD',
       'MLPE', 'MLPFG', 'MLPH', 'MLPI', 'MLPJ', 'MLPK', 'NWAB', 'NWAV',
       'NWLA', 'NWLK', 'NWRE', 'OIP', 'PAP', 'RELP', 'RETP', 'SCH', 'SCHG',
       'SCHL', 'SEMP', 'SEX', 'SSIP', 'SSP', 'WAGP', 'WKHP', 'WKL', 'WKW',
       'WRK', 'YOEP', 'ANC', 'ANC1P', 'ANC2P', 'DECADE', 'DIS', 'DRIVESP',
       'ESP', 'ESR', 'FOD1P', 'FOD2P', 'HICOV', 'HISP', 'INDP', 'JWAP',
       'JWDP', 'LANP', 'MIGPUMA', 'MIGSP', 'MSP', 'NAICSP', 'NATIVITY',
       'NOP', 'OC', 'OCCP', 'PAOC', 'PERNP', 'PINCP', 'POBP', 'POVPIP',
       'POWPUMA', 'POWSP', 'PRIVCOV', 'PUBCOV', 'QTRBI

In [8]:
data = data.drop(['RT', 'SERIALNO', 'SPORDER', 'SEMP', 'ADJINC', 'NAICSP', 'OCCP', 
       'SOCP', 'FAGEP', 'FANCP', 'FCITP', 'FCITWP', 'FCOWP',
       'FDDRSP', 'FDEARP', 'FDEYEP', 'FDISP', 'FDOUTP', 'FDPHYP', 'FDRATP',
       'FDRATXP', 'FDREMP', 'FENGP', 'FESRP', 'FFERP', 'FFODP', 'FGCLP',
       'FGCMP', 'FGCRP', 'FHINS1P', 'FHINS2P', 'FHINS3C', 'FHINS3P',
       'FHINS4C', 'FHINS4P', 'FHINS5C', 'FHINS5P', 'FHINS6P', 'FHINS7P',
       'FHISP', 'FINDP', 'FINTP', 'FJWDP', 'FJWMNP', 'FJWRIP', 'FJWTRP',
       'FLANP', 'FLANXP', 'FMARHDP', 'FMARHMP', 'FMARHTP', 'FMARHWP',
       'FMARHYP', 'FMARP', 'FMIGP', 'FMIGSP', 'FMILPP', 'FMILSP', 'FOCCP',
       'FOIP', 'FPAP', 'FPERNP', 'FPINCP', 'FPOBP', 'FPOWSP', 'FPRIVCOVP',
       'FPUBCOVP', 'FRACP', 'FRELP', 'FRETP', 'FSCHGP', 'FSCHLP', 'FSCHP',
       'FSEMP', 'FSEXP', 'FSSIP', 'FSSP', 'FWAGP', 'FWKHP', 'FWKLP',
       'FWKWP', 'FWRKP', 'FYOEP', 'pwgtp1', 'pwgtp2', 'pwgtp3', 'pwgtp4',
       'pwgtp5', 'pwgtp6', 'pwgtp7', 'pwgtp8', 'pwgtp9', 'pwgtp10',
       'pwgtp11', 'pwgtp12', 'pwgtp13', 'pwgtp14', 'pwgtp15', 'pwgtp16',
       'pwgtp17', 'pwgtp18', 'pwgtp19', 'pwgtp20', 'pwgtp21', 'pwgtp22',
       'pwgtp23', 'pwgtp24', 'pwgtp25', 'pwgtp26', 'pwgtp27', 'pwgtp28',
       'pwgtp29', 'pwgtp30', 'pwgtp31', 'pwgtp32', 'pwgtp33', 'pwgtp34',
       'pwgtp35', 'pwgtp36', 'pwgtp37', 'pwgtp38', 'pwgtp39', 'pwgtp40',
       'pwgtp41', 'pwgtp42', 'pwgtp43', 'pwgtp44', 'pwgtp45', 'pwgtp46',
       'pwgtp47', 'pwgtp48', 'pwgtp49', 'pwgtp50', 'pwgtp51', 'pwgtp52',
       'pwgtp53', 'pwgtp54', 'pwgtp55', 'pwgtp56', 'pwgtp57', 'pwgtp58',
       'pwgtp59', 'pwgtp60', 'pwgtp61', 'pwgtp62', 'pwgtp63', 'pwgtp64',
       'pwgtp65', 'pwgtp66', 'pwgtp67', 'pwgtp68', 'pwgtp69', 'pwgtp70',
       'pwgtp71', 'pwgtp72', 'pwgtp73', 'pwgtp74', 'pwgtp75', 'pwgtp76',
       'pwgtp77', 'pwgtp78', 'pwgtp79', 'pwgtp80'],1)

#Select for Only Adults

In [9]:
data = data[data['AGEP'] >= 18]

In [10]:
data.shape

(2459182, 120)

#Set Up Target Feature

In [11]:
Y = ((data['COW'] == 6) | (data['COW'] == 7))*1
del data['COW']

#Generate Categorical (Short) and Continuous (Long) Feature Lists

In [12]:
col_len_arr = []
for col in data.columns.values:
    col_len = len(np.unique(data[pd.notnull(data[col])][col]))
    col_len_arr.append([col_len, col])

In [13]:
long_col_arr = []
short_col_arr = []

for i in col_len_arr:
    if i[0] >= 70:
        long_col_arr.append(i)
    else:
        short_col_arr.append(i)
print(long_col_arr)
print(short_col_arr)

[[982, 'PUMA'], [1163, 'PWGTP'], [78, 'AGEP'], [73, 'CITWP'], [720, 'INTP'], [138, 'JWMNP'], [81, 'MARHYP'], [609, 'OIP'], [347, 'PAP'], [660, 'RETP'], [295, 'SSIP'], [587, 'SSP'], [907, 'WAGP'], [99, 'WKHP'], [83, 'YOEP'], [231, 'ANC1P'], [230, 'ANC2P'], [173, 'FOD1P'], [172, 'FOD2P'], [267, 'INDP'], [285, 'JWAP'], [150, 'JWDP'], [109, 'LANP'], [211, 'MIGPUMA'], [100, 'MIGSP'], [5148, 'PERNP'], [19858, 'PINCP'], [215, 'POBP'], [502, 'POVPIP'], [217, 'POWPUMA'], [100, 'RAC3P']]
[[51, 'ST'], [5, 'CIT'], [2, 'DDRS'], [2, 'DEAR'], [2, 'DEYE'], [2, 'DOUT'], [2, 'DPHY'], [6, 'DRAT'], [2, 'DRATX'], [2, 'DREM'], [4, 'ENG'], [2, 'FER'], [2, 'GCL'], [5, 'GCM'], [2, 'GCR'], [2, 'HINS1'], [2, 'HINS2'], [2, 'HINS3'], [2, 'HINS4'], [2, 'HINS5'], [2, 'HINS6'], [2, 'HINS7'], [10, 'JWRIP'], [12, 'JWTR'], [2, 'LANX'], [5, 'MAR'], [2, 'MARHD'], [2, 'MARHM'], [3, 'MARHT'], [2, 'MARHW'], [3, 'MIG'], [4, 'MIL'], [2, 'MLPA'], [2, 'MLPB'], [2, 'MLPCD'], [2, 'MLPE'], [2, 'MLPFG'], [2, 'MLPH'], [2, 'MLPI'], [2

#Split the Dataset

In [14]:
data['Y'] = Y
skf = cross_validation.StratifiedKFold(data['Y'], n_folds=10, shuffle = True)

In [15]:
split = []
for i,j in skf:
    split.append(j)

In [16]:
split

[array([     14,      20,      60, ..., 2459165, 2459171, 2459175]),
 array([      4,       8,      37, ..., 2459161, 2459166, 2459168]),
 array([     17,      27,      29, ..., 2459108, 2459131, 2459137]),
 array([     26,      28,      32, ..., 2459149, 2459150, 2459156]),
 array([     18,      21,      31, ..., 2459170, 2459172, 2459180]),
 array([      2,       5,       9, ..., 2459173, 2459178, 2459181]),
 array([      3,      36,      45, ..., 2459120, 2459136, 2459179]),
 array([     15,      16,      19, ..., 2459155, 2459169, 2459176]),
 array([      0,       1,      13, ..., 2459115, 2459129, 2459174]),
 array([      6,       7,      12, ..., 2459151, 2459164, 2459177])]

In [21]:
'''data.loc[split[0]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data01.csv')
data.loc[split[1]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data02.csv')
data.loc[split[2]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data03.csv')
data.loc[split[3]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data04.csv')
data.loc[split[4]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data05.csv')
data.loc[split[5]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data06.csv')
data.loc[split[6]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data07.csv')
data.loc[split[7]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data08.csv')
data.loc[split[8]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data09.csv')
data.loc[split[9]].to_csv(path_or_buf='C:/Users/Mathew/Data Science Project/Split_Data10.csv')'''
#del data

#Test the Training Procedure

In [17]:
path = 'C:/Users/Mathew/Data Science Project/Split_Data01.csv'
frame = pd.read_csv(path)
frame = frame.drop(['PUMA', 'MIGPUMA', 'POWPUMA', 'ANC1P', 'ANC2P', 'FOD1P', 'FOD2P', 'INDP', 'LANP', 'POBP', 'MIGSP', 'RAC3P'], 1)
for feature in short_col_arr:
    frame = pd.concat([frame, pd.get_dummies(frame[feature[1]], prefix = feature[1], dummy_na=True)], axis=1)
    frame = frame.drop(feature[1],1)
frame = frame.fillna(value = -1)
frame = frame.drop('Unnamed: 0',1)


In [18]:
y = frame['Y']
x = frame.drop('Y',1)

n_estimators_grid = [{'n_estimators': list(range(10,26,2))}]
estimator = ensemble.RandomForestClassifier()
est_cv = grid_search.GridSearchCV(estimator, n_estimators_grid, cv = 3).fit(x,y)


In [19]:
print(est_cv.best_score_)
print(est_cv.best_params_)
est = ensemble.RandomForestClassifier(n_estimators=18).fit(x,y)
pd.Series(est.feature_importances_)

0.97104959563
{'n_estimators': 18}


array([  4.99715827e-03,   4.85236145e-03,   5.69972620e-04,
         4.65986699e-02,   3.66320462e-03,   4.03857313e-03,
         8.41538080e-04,   1.89731659e-04,   9.23734505e-04,
         4.40790622e-02,   1.39536556e-02,   4.27818654e-02,
         5.65202061e-03,   8.71581786e-04,   3.48189476e-03,
         3.68309397e-03,   6.23835989e-03,   5.00034450e-02,
         3.81897763e-03,   1.51794443e-04,   3.37957046e-05,
         2.28867815e-04,   1.49983975e-04,   6.73140667e-04,
         2.89667100e-04,   1.54324637e-04,   4.58313545e-05,
         2.09848070e-05,   5.74957338e-04,   2.96952847e-04,
         4.53989325e-05,   8.16297309e-05,   3.35011597e-04,
         2.00769722e-04,   1.26438997e-04,   1.59118267e-04,
         1.77948481e-04,   1.74505014e-04,   8.67422407e-05,
         2.18133051e-04,   2.43717961e-04,   3.28075700e-04,
         2.46487458e-04,   9.93084202e-05,   2.13479909e-04,
         9.43716901e-05,   1.32201856e-04,   1.20741289e-04,
         8.64771553e-05,

#Generate Classifier Functions

In [20]:
splits = ['Split_Data01.csv', 'Split_Data02.csv', 'Split_Data03.csv', 'Split_Data04.csv', 'Split_Data05.csv',
          'Split_Data06.csv', 'Split_Data07.csv', 'Split_Data08.csv', 'Split_Data09.csv']
pickles = ['estimator_pickle_01.pickle', 'estimator_pickle_02.pickle', 'estimator_pickle_03.pickle', 'estimator_pickle_04.pickle', 'estimator_pickle_05.pickle',
           'estimator_pickle_06.pickle', 'estimator_pickle_07.pickle', 'estimator_pickle_08.pickle', 'estimator_pickle_09.pickle']

for i in range(9):
    path = 'C:/Users/Mathew/Data Science Project/' + splits[i]
    frame = pd.read_csv(path)
    frame = frame.drop(['PUMA', 'MIGPUMA', 'POWPUMA', 'ANC1P', 'ANC2P', 'FOD1P', 'FOD2P', 'INDP', 'LANP', 'POBP', 'MIGSP', 'RAC3P'], 1)
    for feature in short_col_arr:
        frame = pd.concat([frame, pd.get_dummies(frame[feature[1]], prefix = feature[1], dummy_na=True)], axis=1)
        frame = frame.drop(feature[1],1)
    frame = frame.fillna(value = -1)
    frame = frame.drop('Unnamed: 0',1)
    
    y = frame['Y']
    x = frame.drop('Y',1)

    n_estimators_grid = [{'n_estimators': list(range(10,26,2))}]
    estimator = ensemble.RandomForestClassifier()
    est_cv = grid_search.GridSearchCV(estimator, n_estimators_grid, cv = 3).fit(x,y)
    
    print(est_cv.best_score_)
    print(est_cv.best_params_)
    
    f = open(pickles[i], 'wb')
    pickle.dump(est_cv, f)
    f.close()
    
    del frame
    
#generate dummies
#add dummies to dataframe
#train model
#save model as a pickle
#delete dataframe

0.970893616019
{'n_estimators': 24}
0.971025404239
{'n_estimators': 22}
0.972291167975
{'n_estimators': 24}
0.970351483604
{'n_estimators': 20}
0.968222597918
{'n_estimators': 18}
0.969641926643
{'n_estimators': 20}
0.969501915709
{'n_estimators': 22}
0.967648686519
{'n_estimators': 16}
0.971566438263
{'n_estimators': 24}


IndexError: list index out of range

#Setup the Test Dataset

In [ ]:
pickles = ['estimator_pickle_01.pickle', 'estimator_pickle_02.pickle', 'estimator_pickle_03.pickle', 'estimator_pickle_04.pickle', 'estimator_pickle_05.pickle',
           'estimator_pickle_06.pickle', 'estimator_pickle_07.pickle', 'estimator_pickle_08.pickle', 'estimator_pickle_09.pickle']
test = pd.read_csv('C:/Users/Mathew/Data Science Project/Split_Data10.csv')
test = test.drop(['PUMA', 'MIGPUMA', 'POWPUMA', 'ANC1P', 'ANC2P', 'FOD1P', 'FOD2P', 'INDP', 'LANP', 'POBP', 'MIGSP', 'RAC3P'], 1)
for feature in short_col_arr:
    test = pd.concat([test, pd.get_dummies(test[feature[1]], prefix = feature[1], dummy_na=True)], axis=1)
    test = test.drop(feature[1],1)
test = test.fillna(value = -1)
test = test.drop('Unnamed: 0',1)
X = test.drop('Y',1)
Y = test['Y']

#Generate Predictions

In [40]:
predictions = []
accuracies = []
output = []
for i in range(9):
    f= open('C:/Users/Mathew/Data Science Project/' + pickles[i], 'rb')
    estimator = pickle.load(f)
    f.close()
    prediction = estimator.predict(X)
    predictions.append(prediction)
    accuracies.append(metrics.accuracy_score(Y,prediction))
predictions = pd.DataFrame(predictions)
for i in range(len(predictions.columns)):
    output.append(stats.mode(predictions[i]).mode)


In [41]:
print(metrics.accuracy_score(Y,output))
print(accuracies)

0.972706821673
[0.96991765167217525, 0.96960512310971814, 0.97097317266613403, 0.97065769572101224, 0.97155695243374252, 0.97136825594320231, 0.97033042524523172, 0.97117955945266221, 0.96942527176717208]


In [45]:
print(confusion_matrix(Y,output))

[[ 93947      0      0]
 [     0 226454    399]
 [     0   8858   9511]]
